// import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'package:food_and_recipe/models/category.dart';
import 'package:food_and_recipe/models/meal.dart';


const DummyCategories = const[
  Category(
    id: 'c1',
    title: 'Indian',
    color: Colors.red,
  ),
  Category(
    id: 'c2',
    title: 'Italian',
    color: Colors.deepPurpleAccent,
  ),
  Category(
    id: 'c3',
    title: 'Chinese',
    color: Colors.amberAccent,
  ),
  Category(
    id: 'c4',
    title: 'Quick & Easy',
    color: Colors.purple,
  ),
  Category(
    id: 'c5',
    title: 'Breakfast',
    color: Colors.lightBlueAccent,
  ),
  Category(
    id: 'c6',
    title: 'Shakes',
    color: Colors.brown,
  ),
  Category(
    id: 'c7',
    title: 'Drinks',
    color: Colors.deepOrange,
  ),
];

const DummyMeals = const [
  Meal(
    id: 'm1',
    categories: ['c1', 'c4'],
    title: 'Chocolate Souffle',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    // imageUrl: 'https://www.shutterstock.com/image-photo/healthy-food-clean-eating-selection-fruit-722718097',
    duration: 45,
    imageUrl: 'assets/images/black screen.jpg',
    ingredients: [
      '1 tbsp Butter',
      '1 tbsp All-purpose flour',
      '1/2 cup Milk (Cold)',
      '100 grams Dark chocolate (75% cocoa)',
      '1 pinch Salt',
      '1/2 tsp Vanilla essence',
      '1 medium size Egg yolk',
      '2 medium size Egg whites',
      '3 tbsp Sugar',
      'Cocoa powder to serve',
    ],
    steps: [
      'Prepping Ramekin',
      'Melting chocolate',
      'Fold Bechamel Chocolate',
      'Making Meringue',
      'Fold Meringue and Base',
      'Transfer to Ramekin',
      'Baking the Souffle',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm2',
    categories: ['c2', 'c3'],
    title: 'Chocolate Souffle',
    affordability: Affordability.Costly,
    complexity: Complexity.Challenging,
    // imageUrl: 'https://www.shutterstock.com/image-photo/healthy-food-clean-eating-selection-fruit-722718097',
    duration: 40,
    imageUrl: 'assets/images/black screen.jpg',
    ingredients: [
      '1 tbsp Butter',
      '1 tbsp All-purpose flour',
      '1/2 cup Milk (Cold)',
      '100 grams Dark chocolate (75% cocoa)',
      '1 pinch Salt',
      '1/2 tsp Vanilla essence',
      '1 medium size Egg yolk',
      '2 medium size Egg whites',
      '3 tbsp Sugar',
      'Cocoa powder to serve',
    ],
    steps: [
      'Prepping Ramekin',
      'Melting chocolate',
      'Fold Bechamel Chocolate',
      'Making Meringue',
      'Fold Meringue and Base',
      'Transfer to Ramekin',
      'Baking the Souffle',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm3',
    categories: ['c4', 'c5'],
    title: 'Chocolate Souffle',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    // imageUrl: 'https://www.shutterstock.com/image-photo/healthy-food-clean-eating-selection-fruit-722718097',
    duration: 35,
    imageUrl: 'assets/images/black screen.jpg',
    ingredients: [
      '1 tbsp Butter',
      '1 tbsp All-purpose flour',
      '1/2 cup Milk (Cold)',
      '100 grams Dark chocolate (75% cocoa)',
      '1 pinch Salt',
      '1/2 tsp Vanilla essence',
      '1 medium size Egg yolk',
      '2 medium size Egg whites',
      '3 tbsp Sugar',
      'Cocoa powder to serve',
    ],
    steps: [
      'Prepping Ramekin',
      'Melting chocolate',
      'Fold Bechamel Chocolate',
      'Making Meringue',
      'Fold Meringue and Base',
      'Transfer to Ramekin',
      'Baking the Souffle',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm4',
    categories: ['c6', 'c7'],
    title: 'Chocolate Souffle',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    // imageUrl: 'https://www.shutterstock.com/image-photo/healthy-food-clean-eating-selection-fruit-722718097',
    duration: 30,
    imageUrl: 'assets/images/black screen.jpg',
    ingredients: [
      '1 tbsp Butter',
      '1 tbsp All-purpose flour',
      '1/2 cup Milk (Cold)',
      '100 grams Dark chocolate (75% cocoa)',
      '1 pinch Salt',
      '1/2 tsp Vanilla essence',
      '1 medium size Egg yolk',
      '2 medium size Egg whites',
      '3 tbsp Sugar',
      'Cocoa powder to serve',
    ],
    steps: [
      'Prepping Ramekin',
      'Melting chocolate',
      'Fold Bechamel Chocolate',
      'Making Meringue',
      'Fold Meringue and Base',
      'Transfer to Ramekin',
      'Baking the Souffle',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: ['c3', 'c6'],
    title: 'Chocolate Souffle',
    affordability: Affordability.Costly,
    complexity: Complexity.Challenging,
    // imageUrl: 'https://www.shutterstock.com/image-photo/healthy-food-clean-eating-selection-fruit-722718097',
    imageUrl: 'assets/images/black screen.jpg',
    duration: 45,
    ingredients: [
      '1 tbsp Butter',
      '1 tbsp All-purpose flour',
      '1/2 cup Milk (Cold)',
      '100 grams Dark chocolate (75% cocoa)',
      '1 pinch Salt',
      '1/2 tsp Vanilla essence',
      '1 medium size Egg yolk',
      '2 medium size Egg whites',
      '3 tbsp Sugar',
      'Cocoa powder to serve',
    ],
    steps: [
      'Prepping Ramekin',
      'Melting chocolate',
      'Fold Bechamel Chocolate',
      'Making Meringue',
      'Fold Meringue and Base',
      'Transfer to Ramekin',
      'Baking the Souffle',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: ['c1', 'c2'],
    title: 'Chocolate Souffle',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    // imageUrl: 'https://www.shutterstock.com/image-photo/healthy-food-clean-eating-selection-fruit-722718097',
    imageUrl: 'assets/images/black screen.jpg',
    duration: 25,
    ingredients: [
      '1 tbsp Butter',
      '1 tbsp All-purpose flour',
      '1/2 cup Milk (Cold)',
      '100 grams Dark chocolate (75% cocoa)',
      '1 pinch Salt',
      '1/2 tsp Vanilla essence',
      '1 medium size Egg yolk',
      '2 medium size Egg whites',
      '3 tbsp Sugar',
      'Cocoa powder to serve',
    ],
    steps: [
      'Prepping Ramekin',
      'Melting chocolate',
      'Fold Bechamel Chocolate',
      'Making Meringue',
      'Fold Meringue and Base',
      'Transfer to Ramekin',
      'Baking the Souffle',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm7',
    categories: ['c5', 'c7'],
    title: 'Chocolate Souffle',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Hard,
    imageUrl: 'assets/images/black screen.jpg',
    // imageUrl: 'https://www.shutterstock.com/image-photo/healthy-food-clean-eating-selection-fruit-722718097',
    duration: 50,
    ingredients: [
      '1 tbsp Butter',
      '1 tbsp All-purpose flour',
      '1/2 cup Milk (Cold)',
      '100 grams Dark chocolate (75% cocoa)',
      '1 pinch Salt',
      '1/2 tsp Vanilla essence',
      '1 medium size Egg yolk',
      '2 medium size Egg whites',
      '3 tbsp Sugar',
      'Cocoa powder to serve',
    ],
    steps: [
      'Prepping Ramekin',
      'Melting chocolate',
      'Fold Bechamel Chocolate',
      'Making Meringue',
      'Fold Meringue and Base',
      'Transfer to Ramekin',
      'Baking the Souffle',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
];